docker_builder:
  name: flutter:$DOCKER_TAG
  env:
    # from https://flutter.dev/docs/development/tools/sdk/releases
    matrix:
      - DOCKER_TAG: latest
        FLUTTER_VERSION: 3.35.1
      - DOCKER_TAG: stable
        FLUTTER_VERSION: 3.35.1
      - DOCKER_TAG: beta
        FLUTTER_VERSION: 3.36.0-0.1.pre
  version_script: docker --version
  setup_script:
    - docker buildx create --name multibuilder
    - docker buildx use multibuilder
    - docker buildx inspect --bootstrap
  ci_script: ./ci.sh
