name: "Check Flutter versions"
on:
  schedule:
    # Every day
    - cron: "0 0 * * 0-6"
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Install yq and jq
      - name: Install yq and jq
        run: |
          mkdir -p ~/bin
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ~/bin/yq
          chmod +x ~/bin/yq
          echo "$HOME/bin" >> $GITHUB_PATH

          sudo apt-get install -y jq curl

      - name: Check for new Flutter versions 
        run: sh scripts/update_flutter_versions.sh

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: docker-container
          install: true

      - name: Build and push Docker images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
        run: |
          # Get the first matrix entry's variables
          DOCKER_TAG=$(yq eval '.docker_builder.env.matrix[0].DOCKER_TAG' .builder.yml)
          FLUTTER_VERSION=$(yq eval '.docker_builder.env.matrix[0].FLUTTER_VERSION' .builder.yml)
          
          LOWERCASE_ACTOR=$(echo "$GITHUB_ACTOR" | tr '[:upper:]' '[:lower:]')
          # Login to GitHub Container Registry
          echo "$GITHUB_TOKEN" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          
          # Build and push if on master branch
          if [ "$BRANCH" = "main" ]; then
            docker buildx build --platform linux/amd64,linux/arm64 --push \
              --tag ghcr.io/$LOWERCASE_ACTOR/flutter-slim:${FLUTTER_VERSION/+/-} \
              --tag ghcr.io/$LOWERCASE_ACTOR/flutter-slim:$DOCKER_TAG \
              --build-arg flutter_version=$FLUTTER_VERSION \
              sdk
          else
            docker buildx build --platform linux/amd64,linux/arm64 \
              --tag ghcr.io/$LOWERCASE_ACTOR/flutter-slim:${FLUTTER_VERSION/+/-} \
              --tag ghcr.io/$LOWERCASE_ACTOR/flutter-slim:$DOCKER_TAG \
              --build-arg flutter_version=$FLUTTER_VERSION \
              sdk
          fi

      # Create a Pull Request if there are any changes.
      # This is automatically checked internally
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: Update Flutter version"
          title: "chore: Update Flutter version"
          branch: "chore/update-flutter-version"
