name: "Check Flutter versions"
on:
  schedule:
    # Every day
    - cron: "0 0 * * 0-6"
  workflow_dispatch:

jobs:
  check_versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write
    steps:
      - uses: actions/checkout@v4

      # Install yq and jq
      - name: Install yq and jq
        run: |
          mkdir -p ~/bin
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O ~/bin/yq
          chmod +x ~/bin/yq
          echo "$HOME/bin" >> $GITHUB_PATH

          sudo apt-get install -y jq curl

      - name: Check for new Flutter versions 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Changed from TOKEN to GITHUB_TOKEN
        run: sh scripts/update_flutter_versions.sh

      - name: Build and push Docker images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ github.ref_name }}
        run: |
          eval $(yq '.docker_builder.env.matrix[]' .builder.yml | \
            jq -r 'to_entries | map("export \(.key)=\(.value)") | join("\n")')
          
          # Make script executable and run it
          chmod +x ci.sh
          ./ci.sh
      # Create a Pull Request if there are any changes.
      # This is automatically checked internally
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: Update Flutter version"
          title: "chore: Update Flutter version"
          branch: "chore/update-flutter-version"
